version: "3.3"
services:
  spark:
    image: fokkodriesprong/docker-pyspark:latest
    volumes:
     - type: bind
       source: .
       target: /root
    tty: true
  db:
    image: timvancann/databricks-cli:latest
    volumes:
      - type: bind
        source: .
        target: /mount
    tty: true
    environment:
      - DATABRICKS_HOST
      - DATABRICKS_TOKEN
